# Generated by Django 5.2 on 2025-04-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfficerPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer_id', models.CharField(max_length=20, unique=True)),
                ('photo', models.ImageField(upload_to='officer_photos/')),
            ],
        ),
    ]
