# Generated by Django 5.2 on 2025-04-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenPhoto',
            fields=[
                ('citizen_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='citizen_photos/')),
            ],
        ),
    ]
